/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Venda;

import Control.ControlaVenda;
import Control.Entidades.ClienteEnt;
import Control.Entidades.FuncionarioEnt;
import Control.Entidades.PecasEnt;
import Control.Entidades.PurificadorEnt;
import Control.Entidades.RefilEnt;
import Control.Entidades.VendaEnt;
import Control.ManipulaVenda;
import Model.ListaTabelas;
import Model.Venda.Manipulacao;
import Model.Venda.ProcuraQnt;
import View.Pagamento.Cartao;
import View.Pagamento.Cheque;
import View.cadastro.edicao.CadastroCliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julio
 */
public class Vendas extends javax.swing.JFrame {

    /**
     * Creates new form Vendas
     */
    public Vendas() {
        initComponents();
        read();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    VendaEnt v = new VendaEnt();
    PurificadorEnt a = new PurificadorEnt();
    ClienteEnt c = new ClienteEnt();
    FuncionarioEnt f = new FuncionarioEnt();
    RefilEnt r = new RefilEnt();
    PecasEnt p = new PecasEnt();
    ControlaVenda con = new ControlaVenda();
    ProcuraQnt pr = new ProcuraQnt();
    Manipulacao ma = new Manipulacao();

    int q = 0;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("tcc?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cliente c");
        clienteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : clienteQuery.getResultList();
        clienteQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cliente c");
        clienteList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : clienteQuery1.getResultList();
        funcionarioQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Funcionario f");
        funcionarioList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : funcionarioQuery.getResultList();
        purificadoresQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Purificadores p");
        purificadoresList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : purificadoresQuery.getResultList();
        refisQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT r FROM Refis r");
        refisList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : refisQuery.getResultList();
        pecasQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Pecas p");
        pecasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pecasQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        tabelaprincipal = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CliPesq = new javax.swing.JTextField();
        pesquisa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ConfirmaCliente = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        Cli = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Vend = new javax.swing.JTable();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        PuriText = new javax.swing.JTextField();
        pesquisaPurificador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        quantidade = new javax.swing.JTextField();
        ConfirmaPurificador8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        puri = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        RefilText = new javax.swing.JTextField();
        pesquisaRefil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        qnt2 = new javax.swing.JTextField();
        ConfirmaRefil = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        filtro = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        ConfirmaPecas = new javax.swing.JButton();
        PecasText = new javax.swing.JTextField();
        pesquisaPecas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        qnt3 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Pec = new javax.swing.JTable();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        Cheque = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Avista = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cartao = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-Sell Stock-96.png"))); // NOI18N

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Venda/icons8-Back-96.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        tabelaprincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pesquisa, informe o nome:");

        CliPesq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-Search-100.png"))); // NOI18N
        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Venda/icons8-administrator-male-64.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ConfirmaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/estoque/icons8-checked-96.png"))); // NOI18N
        ConfirmaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaClienteActionPerformed(evt);
            }
        });

        Cli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cidade", "Telefone", "Bairro", "Rua", "Número"
            }
        ));
        jScrollPane6.setViewportView(Cli);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(CliPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(ConfirmaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CliPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Selecione o cliente:", jPanel2);

        tabelaprincipal.addTab("Cliente", jTabbedPane2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/estoque/icons8-checked-96.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Vend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, funcionarioList, Vend);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cargo}"));
        columnBinding.setColumnName("Cargo");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(Vend);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane3.addTab("Informe o vendedor", jPanel3);

        tabelaprincipal.addTab("Vendedor", jTabbedPane3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        PuriText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pesquisaPurificador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-Search-100.png"))); // NOI18N
        pesquisaPurificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaPurificadorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Pesquisa, informe o modelo:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Quantidade:");

        quantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantidade.setText("1");

        ConfirmaPurificador8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/estoque/icons8-checked-96.png"))); // NOI18N
        ConfirmaPurificador8.setToolTipText("");
        ConfirmaPurificador8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaPurificador8ConfirmaPurificadorActionPerformed(evt);
            }
        });

        puri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Cor", "Preco"
            }
        ));
        jScrollPane2.setViewportView(puri);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(PuriText, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisaPurificador, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(ConfirmaPurificador8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisaPurificador, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PuriText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmaPurificador8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Purificador", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        RefilText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pesquisaRefil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-Search-100.png"))); // NOI18N
        pesquisaRefil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaRefilActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Pesquisa, informe o modelo:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Quantidade:");

        qnt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qnt2.setText("1");

        ConfirmaRefil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/estoque/icons8-checked-96.png"))); // NOI18N
        ConfirmaRefil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaRefilActionPerformed(evt);
            }
        });

        filtro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Preco"
            }
        ));
        jScrollPane3.setViewportView(filtro);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(RefilText, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesquisaRefil, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(qnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(422, 422, 422)
                                .addComponent(ConfirmaRefil, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 177, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisaRefil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RefilText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(qnt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmaRefil, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Refil", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        ConfirmaPecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/estoque/icons8-checked-96.png"))); // NOI18N
        ConfirmaPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaPecasActionPerformed(evt);
            }
        });

        PecasText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pesquisaPecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-Search-100.png"))); // NOI18N
        pesquisaPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaPecasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Pesquisa, informe o nome:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Quantidade:");

        qnt3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qnt3.setText("1");

        Pec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Descicao", "Preco"
            }
        ));
        jScrollPane4.setViewportView(Pec);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(421, 421, 421)
                                .addComponent(ConfirmaPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(PecasText, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesquisaPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(qnt3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 177, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisaPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PecasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(qnt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmaPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Peças", jPanel6);

        tabelaprincipal.addTab("Produto", jTabbedPane4);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        Cheque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Venda/icons8-Check Book-104.png"))); // NOI18N
        Cheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChequeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Cheque");

        Avista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Venda/icons8-Money-96.png"))); // NOI18N
        Avista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvistaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cartão");

        cartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Venda/icons8-Bank Cards-100.png"))); // NOI18N
        cartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("A vista");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18))
                    .addComponent(Avista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)))
                .addGap(112, 112, 112)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cheque, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)))
                .addGap(285, 285, 285))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cheque, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartao, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Avista, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(114, 114, 114)))
                        .addGap(8, 8, 8)))
                .addGap(276, 276, 276))
        );

        jTabbedPane5.addTab("Selecione o método:", jPanel7);

        tabelaprincipal.addTab("Método de Pagamento", jTabbedPane5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaprincipal)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(tabelaprincipal)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        MenuDeVenda m = new MenuDeVenda();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed
        try {
            readJtableCli(CliPesq.getText());
        } catch (Exception erro) {
            System.out.println(erro);

        }
    }//GEN-LAST:event_pesquisaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CadastroCliente c = new CadastroCliente();
        c.setCod(2);
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int selecionada = Vend.getSelectedRow();
        if (selecionada == -1) {
            return; //Não tem nada selecionado
        }
        f.setNome(Vend.getValueAt(selecionada, 0).toString());
        f.setCargo(Vend.getValueAt(selecionada, 1).toString());

        tabelaprincipal.setSelectedIndex(2);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChequeActionPerformed
        Cheque c = new Cheque();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_ChequeActionPerformed

    private void AvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvistaActionPerformed
        ManipulaVenda m = new ManipulaVenda();

        v.setMetodo("A Vista");
        con.Manipula("A Vista", 1);
        dispose();
    }//GEN-LAST:event_AvistaActionPerformed

    private void cartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaoActionPerformed
        Cartao c = new Cartao();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_cartaoActionPerformed

    private void pesquisaPurificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaPurificadorActionPerformed
        readPuriTabelaPesquisa(PuriText.getText());
        PuriText.setText("");
    }//GEN-LAST:event_pesquisaPurificadorActionPerformed

    private void ConfirmaPurificador8ConfirmaPurificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaPurificador8ConfirmaPurificadorActionPerformed
        int selecionada = puri.getSelectedRow();
        if (selecionada == -1) {
            return; //Não tem nada selecionado
        }

        a.setModelo(puri.getValueAt(selecionada, 0).toString());
        a.setCor(puri.getValueAt(selecionada, 1).toString());
        a.setPreco((float) puri.getValueAt(selecionada, 2));
        a.setQnt(Integer.parseInt(quantidade.getText()));
        q = (Integer.parseInt(quantidade.getText()));
        v.setCod(1);
        v.setId(ma.capturaIdP(a));

        if (pr.QntProcuraP(v) < q) {
            JOptionPane.showMessageDialog(null, "A quantidade de em estoque é inferior a quantidade selecionada\nPor favor, escolha outro produto! \n" + "A quantidade"
                    + " desse produto disponível é de: " + pr.QntProcuraP(v));
        } else {
            con.prod(p, a, r, v, f, c);
        }

        quantidade.setText("1");

    }//GEN-LAST:event_ConfirmaPurificador8ConfirmaPurificadorActionPerformed

    private void pesquisaRefilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaRefilActionPerformed
        readPuriRefisTabelaPesquisa(RefilText.getText());
        RefilText.setText("");
    }//GEN-LAST:event_pesquisaRefilActionPerformed

    private void ConfirmaRefilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaRefilActionPerformed
        int selecionada = filtro.getSelectedRow();
        if (selecionada == -1) {
            return; //NÃ£o tem nada selecionado
        }
        v.setCod(2);
        r.setModelo(filtro.getValueAt(selecionada, 0).toString());
        r.setPreco((float) filtro.getValueAt(selecionada, 1));
        r.setQnt(Integer.parseInt(qnt2.getText()));
        q = (Integer.parseInt(quantidade.getText()));
        v.setCod(2);
        v.setId(ma.capturaIdR(r));
        if (pr.QntProcuraP(v) < q) {
            JOptionPane.showMessageDialog(null, "A quantidade de em estoque Ã© inferior a quantidade selecionada\nPor favor, escolha outro produto! \n" + "A quantidade"
                    + " desse produto disponÃ­vel Ã© de: " + r.getQnt());
        } else {
            con.prod(p, a, r, v, f, c);
        }    }//GEN-LAST:event_ConfirmaRefilActionPerformed

    private void ConfirmaPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaPecasActionPerformed
        int selecionada = Pec.getSelectedRow();
        if (selecionada == -1) {
            return; //Não tem nada selecionado
        }
        p.setNome(Pec.getValueAt(selecionada, 0).toString());
        p.setDescricao(Pec.getValueAt(selecionada, 1).toString());
        p.setPreco((float) Pec.getValueAt(selecionada, 2));
        p.setQnt(Integer.parseInt(qnt3.getText()));
        q = (Integer.parseInt(quantidade.getText()));
        v.setCod(3);
        v.setId(ma.capturaIdPe(p));
        if (pr.QntProcuraPe(v) < q) {
            JOptionPane.showMessageDialog(null, "A quantidade de em estoque é inferior a quantidade selecionada\nPor favor, escolha outro produto! \n" + "A quantidade"
                    + " desse produto disponível é de: " + pr.QntProcuraPe(v));
        } else {
            con.prod(p, a, r, v, f, c);
        }

    }//GEN-LAST:event_ConfirmaPecasActionPerformed

    private void pesquisaPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaPecasActionPerformed
        readPecasTabela1Pesquisa(PecasText.getText());
        PecasText.setText("");
    }//GEN-LAST:event_pesquisaPecasActionPerformed

    private void ConfirmaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaClienteActionPerformed
        int selecionada = Cli.getSelectedRow();
        if (selecionada == -1) {
            return; //Não tem nada selecionado
        }

        c.setNome(Cli.getValueAt(selecionada, 0).toString());
        c.setCidade(Cli.getValueAt(selecionada, 1).toString());
        c.setTelefone(Cli.getValueAt(selecionada, 2).toString());
        c.setBairro(Cli.getValueAt(selecionada, 3).toString());
        c.setRua(Cli.getValueAt(selecionada, 4).toString());
        c.setNumero(Cli.getValueAt(selecionada, 5).toString());
        v.setCliente(c.getNome());
        v.setTelefone(c.getTelefone());
        v.setCidade(c.getCidade());

        v.setEndereco("Rua: " + c.getRua() + " Número: " + c.getNumero() + " Bairro: " + c.getBairro() + " Cidade: " + c.getCidade());
        System.out.println(v.getEndereco());
        tabelaprincipal.setSelectedIndex(1);
    }//GEN-LAST:event_ConfirmaClienteActionPerformed

    public void read() {
        readJCli();
        readPuriTabela();
        readPuriRefisTabela();
        readPecasTabela1();

    }

    ///////////////////////////////////preencher tabelas///////////////////////////////
    public void readPuriTabela() {
        DefaultTableModel modelo = (DefaultTableModel) puri.getModel();
        modelo.setNumRows(0);
        ListaTabelas l = new ListaTabelas();

        for (PurificadorEnt p : l.getPurificadores()) {
            modelo.addRow(new Object[]{
                p.getModelo(),
                p.getCor(),
                p.getPreco()});
        }
    }

    public void readPuriRefisTabela() {
        DefaultTableModel modelo = (DefaultTableModel) filtro.getModel();
        modelo.setNumRows(0);
        ListaTabelas l = new ListaTabelas();

        for (RefilEnt r : l.getRefis()) {
            modelo.addRow(new Object[]{
                r.getModelo(),
                r.getPreco()});
        }
    }

    public void readPecasTabela1() {
        DefaultTableModel modelo = (DefaultTableModel) Pec.getModel();
        modelo.setNumRows(0);
        ListaTabelas l = new ListaTabelas();

        for (PecasEnt p : l.getPecas()) {
            modelo.addRow(new Object[]{
                p.getNome(),
                p.getDescricao(),
                p.getPreco()
            });
        }
    }

    public void readJCli() {
        DefaultTableModel modelo = (DefaultTableModel) Cli.getModel();
        modelo.setNumRows(0);
        ListaTabelas l = new ListaTabelas();

        for (ClienteEnt c : l.getClientes()) {
            modelo.addRow(new Object[]{
                c.getNome(),
                c.getCidade(),
                c.getTelefone(),
                c.getBairro(),
                c.getRua(),
                c.getNumero()

            });

        }
    }

//////////////////////////////////////////////pesquisa//////////////////////////////////////////////  
    public void readJtableCli(String nome) {
        DefaultTableModel modelo = (DefaultTableModel) Cli.getModel();
        modelo.setNumRows(0);
        ListaTabelas l = new ListaTabelas();

        for (ClienteEnt c : l.getPesquisaClientes(nome)) {
            modelo.addRow(new Object[]{
                c.getNome(),
                c.getCidade(),
                c.getTelefone(),
                c.getBairro(),
                c.getRua()

            });

        }
    }

    public void readPuriTabelaPesquisa(String mod) {
        DefaultTableModel modelo = (DefaultTableModel) puri.getModel();
        modelo.setNumRows(0);
        ListaTabelas l = new ListaTabelas();

        for (PurificadorEnt p : l.getPesquisaPurificadores(mod)) {
            modelo.addRow(new Object[]{
                p.getModelo(),
                p.getCor(),
                p.getPreco()});
        }
    }

    public void readPuriRefisTabelaPesquisa(String mod) {
        DefaultTableModel modelo = (DefaultTableModel) filtro.getModel();
        modelo.setNumRows(0);
        ListaTabelas l = new ListaTabelas();

        for (RefilEnt r : l.getPesquisaRefis(mod)) {
            modelo.addRow(new Object[]{
                r.getModelo(),
                r.getPreco()});
        }
    }

    public void readPecasTabela1Pesquisa(String nome) {
        DefaultTableModel modelo = (DefaultTableModel) Pec.getModel();
        modelo.setNumRows(0);
        ListaTabelas l = new ListaTabelas();

        for (PecasEnt p : l.getPesquisaPecas(nome)) {
            modelo.addRow(new Object[]{
                p.getNome(),
                p.getDescricao(),
                p.getPreco()
            });
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Avista;
    private javax.swing.JButton Cheque;
    private javax.swing.JTable Cli;
    private javax.swing.JTextField CliPesq;
    private javax.swing.JButton ConfirmaCliente;
    private javax.swing.JButton ConfirmaPecas;
    private javax.swing.JButton ConfirmaPurificador8;
    private javax.swing.JButton ConfirmaRefil;
    private javax.swing.JTable Pec;
    private javax.swing.JTextField PecasText;
    private javax.swing.JTextField PuriText;
    private javax.swing.JTextField RefilText;
    private javax.swing.JTable Vend;
    private javax.swing.JButton cartao;
    private java.util.List<View.Venda.Cliente> clienteList;
    private java.util.List<View.Venda.Cliente> clienteList1;
    private javax.persistence.Query clienteQuery;
    private javax.persistence.Query clienteQuery1;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTable filtro;
    private java.util.List<View.Venda.Funcionario> funcionarioList;
    private javax.persistence.Query funcionarioQuery;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private java.util.List<View.Venda.Pecas> pecasList;
    private javax.persistence.Query pecasQuery;
    private javax.swing.JButton pesquisa;
    private javax.swing.JButton pesquisaPecas;
    private javax.swing.JButton pesquisaPurificador;
    private javax.swing.JButton pesquisaRefil;
    private javax.swing.JTable puri;
    private java.util.List<View.Venda.Purificadores> purificadoresList;
    private javax.persistence.Query purificadoresQuery;
    private javax.swing.JTextField qnt2;
    private javax.swing.JTextField qnt3;
    private javax.swing.JTextField quantidade;
    private java.util.List<View.Venda.Refis> refisList;
    private javax.persistence.Query refisQuery;
    private javax.swing.JTabbedPane tabelaprincipal;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
