/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.cadastro.edicao.CadastroPurificador;
import View.cadastro.edicao.CadastroCliente;
import View.cadastro.edicao.CadastroFunc;
import View.cadastro.edicao.CadastroPecas;
import View.cadastro.edicao.CadastroRefil;

/**
 *
 * @author Julio
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Filtroo = new javax.swing.JButton();
        Apararelho = new javax.swing.JButton();
        Func = new javax.swing.JButton();
        precas = new javax.swing.JButton();
        clientes = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Purificadores");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 13, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Refís");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 13, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Peças");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 313, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Funcionários");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 300, -1, -1));

        Filtroo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/filtro.jpg"))); // NOI18N
        Filtroo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrooActionPerformed(evt);
            }
        });
        jPanel2.add(Filtroo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 150, 150));

        Apararelho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/purificador.jpg"))); // NOI18N
        Apararelho.setText("jButton2");
        Apararelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApararelhoActionPerformed(evt);
            }
        });
        jPanel2.add(Apararelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 53, 150, 188));

        Func.setBackground(new java.awt.Color(255, 255, 255));
        Func.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/funcionario.png"))); // NOI18N
        Func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncActionPerformed(evt);
            }
        });
        jPanel2.add(Func, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 329, 181, 208));

        precas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/moretools.png"))); // NOI18N
        precas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precasActionPerformed(evt);
            }
        });
        jPanel2.add(precas, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 353, 186, 173));

        clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/cliente.png"))); // NOI18N
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        jPanel2.add(clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 53, 150, 178));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Clientes");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 13, -1, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/voltarbranco.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/contactform_icon.png"))); // NOI18N
        jLabel6.setText("Foto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(86, 86, 86)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void precasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precasActionPerformed
        CadastroPecas c = new CadastroPecas();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_precasActionPerformed

    private void FuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncActionPerformed
        CadastroFunc c = new CadastroFunc();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_FuncActionPerformed

    private void ApararelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApararelhoActionPerformed
        CadastroPurificador c = new CadastroPurificador();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_ApararelhoActionPerformed

    private void FiltrooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrooActionPerformed
        CadastroRefil c = new CadastroRefil();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_FiltrooActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuDef m = new MenuDef();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        CadastroCliente c = new CadastroCliente();
        c.setCod(1);
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_clientesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apararelho;
    private javax.swing.JButton Filtroo;
    private javax.swing.JButton Func;
    private javax.swing.JButton clientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton precas;
    // End of variables declaration//GEN-END:variables
}
